 # Change these first
owner: ntdev-technology # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BFRPortal
    url: https://bfrportal.nl/
    assignees:
    - deadlykeyboard
    headers:
      - "User-Agent: Mozilla/5.0"

#assignees:
#  - tommie1236
#  - deadlykeyboard

status-website:
  baseUrl: /upptime
  name: ntdev-technology webservers
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
